Repository joke2k/faker, pull requests merged in 2022-02, with the labels that each got.

#1603 Remove empty string in Korean job list.
  faker/providers/job/ko_KR/__init__.py
Labels: bug

#1605 Use os.urandom in binary if unseeded
  faker/generator.py
  faker/providers/misc/__init__.py
Labels: bump-version:major

#1616 Fixes #1352 Missing tests in various address providers
  tests/providers/test_address.py
Labels: waiting on feedback

#1608 Task/jabertuhin/1519/add loremprovider for bn bd
  faker/providers/lorem/bn_BD/__init__.py
  tests/providers/test_lorem.py
Labels: bump-version:minor
