Repository joke2k/faker, pull requests merged in 2023-02, with the labels that each got.

#1706 :sparkles: - Emoji provider added (#1686).
  faker/providers/emoji/__init__.py
  faker/providers/emoji/en_US/__init__.py
  tests/providers/test_emoji.py
  tests/providers/test_person.py
  tests/utils/test_utils.py
Labels: needs:linting

#1739 Sort and add new Arabic words
  faker/providers/color/ar_PS/__init__.py
  faker/providers/person/ar_AA/__init__.py
Labels: stale

#1789 Remove deprecated placeimg image provider
  faker/providers/internet/__init__.py
Labels: bump-version:major
