Repository joke2k/faker, pull requests merged in 2023-01, with the labels that each got.

#1769 Feature/allow passing optional json encoder
  faker/providers/misc/__init__.py
  tests/providers/test_misc.py
Labels: enhancement, bump-version:minor

#1766 Add fr ca date time provider
  faker/providers/date_time/fr_CA/__init__.py
  tests/providers/test_date_time.py
Labels: provider, bump-version:minor

#1781 Belgium person issue #1778
  faker/providers/person/fr_BE/__init__.py
  faker/providers/person/nl_BE/__init__.py
  tests/providers/test_person.py
Labels: bump-version:minor

#1763 Update spanish phone number formats
  faker/providers/phone_number/es_ES/__init__.py
Labels: bump-version:minor
